### ISSUE TITLE
Can I have your email address?

### ISSUE THREAD

**Issue by NewDriverLee** [MAC-AutoML/OMPQ#4]
Hi, are you the first author of the paper "_OMPQ: Orthogonal Mixed Precision Quantization_"? I am very interested in your work. Can I have your email address so that we can have some personal communications?

**Comment by BobxmuMa** [comment]
> Hi, are you the first author of the paper "_OMPQ: Orthogonal Mixed Precision Quantization_"? I am very interested in your work. Can I have your email address so that we can have some personal communications?

bobma@stu.xmu.edu.cn
